services:
  app:
    image: demo-gofiber
    container_name: demo-gofiber
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8080:8080" # port for http/1.0 (http://)
      - "9090:9090" # port for http/2.0 (grpc://)
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:15.1-alpine
    container_name: demo-gofiber-db
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.utf8
      POSTGRES_DB: demo-gofiber-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
volumes:
  db_data:
    driver: local
